apiVersion: nova.openstack.org/v1beta1
kind: NovaMetadata
metadata:
  name: novametadata-sample
spec:
  apiDatabaseHostname: openstack
  apiMessageBusSecretName: rabbitmq-transport-url-nova-api-transport
  containerImage: quay.io/tripleozedcentos9/openstack-nova-api:current-tripleo
  keystoneAuthURL: http://keystone-public-openstack.apps-crc.testing
  secret: osp-secret
